accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from accounts.views import (
    signup,
)


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

closet/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("section/", include("section.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("list_section")), name="home"),
    path("clothe/", include("clothe.urls")),
    path("accounts/", include("accounts.urls")),
]

clothe/urls.py
from django.urls import path
from clothe.views import ClotheCreateView, ClotheListView, ClotheUpdateView,ClotheDeleteView

urlpatterns = [
    path("create/", ClotheCreateView.as_view(), name="create_clothe"),
    path("mine/", ClotheListView.as_view(), name="show_my_clothe"),
    path("<int:pk>/complete/", ClotheUpdateView.as_view(), name="complete_clothe"),
    path("<int:pk>/delete/", ClotheDeleteView.as_view(), name="delete_clothe"),
    # path("ootd/", OutfitList, name="ootd"),
]

section/urls.py
from django.urls import path
from section.views import (
    SectionListView,
    SectionDetailView,
    #SectionCreateView,
    OutfitListView,
)

urlpatterns = [
    path("", SectionListView.as_view(), name="list_section"),
    path("<int:pk>/", SectionDetailView.as_view(), name="show_section"),
    #path("create/", SectionCreateView.as_view(), name="create_section"),
    path("ootd/", OutfitListView.as_view(), name="ootd"),
]

clothe/models.py
from django.db import models
from django.conf import settings
from section.models import Section

USER_MODEL = settings.AUTH_USER_MODEL
# Create your models here.


class Clothe(models.Model):
    name = models.CharField(max_length=200)
    image = models.URLField(null = True, blank = True)
    is_laundry = models.BooleanField(default=False)
    section = models.ForeignKey(
        Section, related_name="clothe", on_delete=models.CASCADE
    )
    owner = models.ForeignKey(
        USER_MODEL,
        null=True,
        related_name="clothe",
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.name

section/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class Section(models.Model):
    name = models.CharField(max_length=200)
    owner = models.ManyToManyField(
        USER_MODEL,
        related_name="section"
    )
    
    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.models import User


# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password1"]
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm(request.POST)
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

clothe/views.py
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Clothe
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView, CreateView
from django.shortcuts import render
import random
# Create your views here.


class ClotheCreateView(LoginRequiredMixin, CreateView):
    model = Clothe
    template_name = "clothe/create.html"
    fields = ["name","image","section"]

    def get_success_url(self):
        return reverse_lazy("list_section") #args=[self.object.id])


class ClotheListView(LoginRequiredMixin, ListView):
    model = Clothe
    template_name = "clothe/list.html"

    def get_queryset(self):
        return Clothe.objects.filter(owner=self.request.user)


class ClotheUpdateView(LoginRequiredMixin, UpdateView):
    model = Clothe
    fields = ["is_laundry"]

    def get_success_url(self):
        return reverse_lazy("home")

class ClotheDeleteView(LoginRequiredMixin, DeleteView):
    model = Clothe
    template_name="clothe/delete.html"
    success_url = reverse_lazy("home")

# def OutfitList(request):
#     Outfit = list(Clothe.objects.all())

#     Outfit = random.sample(Outfit,1)

#     return render(request, 'section/ootd.html', {'Outfit': Outfit})

section/views.py
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
import random
from django.shortcuts import render
from clothe.models import Clothe

from .models import Section



# Create your views here.
class SectionListView(LoginRequiredMixin, ListView):
    model = Section
    template_name = "section/list.html"

    def get_queryset(self):
        return Section.objects.filter(owner=self.request.user)

class SectionDetailView(LoginRequiredMixin, DetailView):
    model = Section
    template_name = "section/detail.html"

# class ProjectCreateView(LoginRequiredMixin, CreateView):
#     model = Project
#     template_name = "projects/create.html"
#     fields = ["name", "description", "members"]

#     def get_success_url(self):
#         return reverse_lazy("show_project", args=[self.object.id])

class OutfitListView(LoginRequiredMixin, ListView):
    model = Section
    template_name = "section/ootd.html"


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # nulist = []
        # for clothing in Section.objects.all():
        #     for item in Clothe.objects.all():
        #         if item.id == clothing.id:
        #             pass
        # context['stuff'] = nulist

        toplist = []
        pantlist = []
        shoelist = []
        for clothings in Clothe.objects.all():
            if clothings.section_id == 1 and clothings.is_laundry == 0:
                toplist.append(clothings)
            elif clothings.section_id == 2 and clothings.is_laundry == 0:
                pantlist.append(clothings)
            elif clothings.section_id == 3 and clothings.is_laundry == 0:
                shoelist.append(clothings)

        context['top']  = random.choice(toplist)
        context['pant'] = random.choice(pantlist)
        context['shoe'] = random.choice(shoelist)

        return context

        

    def get_queryset(self):
        return Section.objects.filter(owner=self.request.user)

clothe/templates/clothe/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>New Clothing</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

clothe/templates/clothe/delete.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ clothe.name }}"?</p>
            {{ form.as_p }}
            <div class="control">
                <button class="button">Delete</button>
            </div>
        </form>
    </main>
{% endblock content %}

clothe/templates/clothe/list.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <p>{{ section.clothe.all }} </p>
        <div>
            <h1>My Clothes</h1>
            {% if clothe_list %}
                <table>
                    <thead>

                    </thead>
                    <tbody>
                        {% for clothe in clothe_list %}
                            <tr>
                                {% if clothe.image and not clothe.is_laundry %}
                                <td class="container">
                                    <form method ="post" action ="{% url 'complete_clothe' clothe.id %}">
                                        {% csrf_token %}
                                        <input type="image" src="{{ clothe.image }}" class="clothe-image" value="True" alt = "Sumbit">
                                        <input type="hidden" name="is_laundry" value = "True">
                                        <div class="overlay">
                                            <div class="text">{{ clothe.name }}</div>
                                        </div> 
                                    </form>
                                </td>

                                {% elif clothe.image and clothe.is_laundry%}
                                    <td class="container">
                                        <form method ="post" action ="{% url 'complete_clothe' clothe.id %}">
                                            {% csrf_token %}
                                            <input type="image" src="{{ clothe.image }}" class="clothe-image-dark" value="False" alt = "Sumbit">
                                            <input type="hidden" name="is_laundry" value = "False">
                                            {% comment %} <img src="{{ clothe.image }}" class="clothe-image-dark"> {% endcomment %}
                                            <div class="text">In Laundry</div>
                                            <div class="overlay">
                                                <div class="text">{{ clothe.name }}</div>
                                            </div>
                                        </form> 
                                    </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>You have no clothes</p>
            {% endif %}
        </div>
    </main>
{% endblock content %}

section/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>WSIWT</title>
        <link rel="stylesheet" href="{% static 'css/app.css' %}">
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li><a href="{% url 'home' %}">Wardrobe</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'ootd' %}">Outfit of The Day</a></li>
                        <li style="float:right"><a href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li style="float:right"><a href="{% url 'signup' %}">Signup</a></li>
                        <li style="float:right"><a href="{% url 'login' %}">Login</a></li>
                    {% endif %}
                </ul>
                {% comment %} <iframe width="25%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1142727544&color=%23ff5500&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe>
                <div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;">
                <a href="https://soundcloud.com/kijugo" title="Kijugo" target="_blank" style="color: #cccccc; text-decoration: none;">Kijugo</a> · <a href="https://soundcloud.com/kijugo/sets/anime-lofi" title="is it okay if it&#x27;s lofi?" target="_blank" style="color: #cccccc; text-decoration: none;">is it okay if it&#x27;s lofi?</a></div> {% endcomment %}
            </nav>
        </header>
            
        {% block content %}
        {% endblock content %}
    </body>
</html>   

section/templates/section/list.html
{% extends 'base.html' %}


{% block content %}
    <main>
        <h1 class="retro">My Wardrobe</h1>
        <div>
            <p><a href="{% url 'create_clothe' %}">Add Item</a></p>
        </div>
        <div>
            {% if section_list %}
                <table>
                    {% for section in section_list %}
                    <thead>
                        <th class="retro">{{ section.name }}</th>
                    </thead>
                    <tbody>
                        <tr>
                            {% if section.clothe.all %}
                                {% for clothe in section.clothe.all %}
                                <tr>
                                    {% if clothe.image and not clothe.is_laundry %}
                                    <td class="container">
                                        <form method ="post" action ="{% url 'complete_clothe' clothe.id %}">
                                            {% csrf_token %}
                                            <input type="image" src="{{ clothe.image }}" class="clothe-image" value="True" alt = "Sumbit">
                                            <input type="hidden" name="is_laundry" value = "True">
                                            <div class="overlay">
                                                <div class="text">{{ clothe.name }}</div>
                                            </div> 
                                        </form>
                                    </td>
    
                                    {% elif clothe.image and clothe.is_laundry%}
                                        <td class="container">
                                            <form method ="post" action ="{% url 'complete_clothe' clothe.id %}">
                                                {% csrf_token %}
                                                <input type="image" src="{{ clothe.image }}" class="clothe-image-dark" value="False" alt = "Sumbit">
                                                <input type="hidden" name="is_laundry" value = "False">
                                                {% comment %} <img src="{{ clothe.image }}" class="clothe-image-dark"> {% endcomment %}
                                                <div class="text">In Laundry</div>
                                                <div class="overlay">
                                                    <div class="text">{{ clothe.name }}</div>
                                                </div>
                                            </form> 
                                        </td>
                                    {% endif %}
                                    </tr>
                                    {% comment %} {% if not clothe.is_laundry %} 
                                    <td class="container">
                                        <img src="{{ clothe.image }}" class="clothe-image">
                                        <div class="overlay">
                                            <div class="text">{{ clothe.name }}</div>
                                        </div>
                                    </td>
                                    {% endif %}  {% endcomment %}
                                {% endfor %}
                            {% endif %}
                        </tr>
                    </tbody>
                    {% endfor %}
                </table>
            {% else %}
                <p>Where are your clothes?</p>
            {% endif %}
        </div>
    </main>
{% endblock content %}

section/templates/section/ootd.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <h1>Outfit of The Day</h1>
        <div>
            {% if section_list %}
                <table>
                    {% for section in section_list %}
                    <thead>
                        <th class="retro">{{ section.name }}</th>
                    </thead>
                    <tbody>
                        <tr>
                            {% if section.id == 1 %}
                            <td class="container">
                                <img src="{{ top.image }}" class="clothe-image">
                                <div class="overlay">
                                    <div class="text">{{ top.name }}</div>
                                </div> 
                            </td>
                            {% elif section.id == 2 %}
                            <td class="container">
                                <img src="{{ pant.image }}" class="clothe-image">
                                <div class="overlay">
                                    <div class="text">{{ pant.name }}</div>
                                </div> 
                            </td>
                            {% elif section.id == 3 %}
                            <td class="container">
                                <img src="{{ shoe.image }}" class="clothe-image">
                                <div class="overlay">
                                    <div class="text">{{ shoe.name }}</div>
                                </div> 
                            </td>
                            {% endif %}

                            {% comment %} {% if section.clothe.all %}
                                {% for clothe in section.clothe.all %}
                                <tr>
                                    {% if clothe.image and not clothe.is_laundry %}
                                    <td class="container">
                                            <img src="{{ clothe.image }}" class="clothe-image">
                                            <div class="overlay">
                                                <div class="text">{{ clothe.name }}</div>
                                            </div> 
                                    </td>
                                    {% endif %}
                                </tr>
                                {% endfor %}
                            {% endif %} {% endcomment %}
                        </tr>
                    </tbody>
                    {% endfor %}
                </table>
            {% else %}
                <p>Where are your clothes?</p>
            {% endif %}
        </div>
    </main>
{% endblock content %}